server:
  port: 8080

spring:
  datasource:
    hikari:
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: ${application.spring.datasource.url}
      username: ${application.spring.datasource.username}
      password: ${application.spring.datasource.password}

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  cloud:
    aws:
      s3:
        bucket: ${spring.cloud.ncp.s3.bucket}
      credentials:
        accessKey: ${spring.cloud.aws.credentials.access-key}
        secretKey: ${spring.cloud.aws.credentials.secret-key}
      region:
        static: ap-northeast-2
        auto: false
      stack:
        auto: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${google.client-id}
            client-secret: ${google.client-secret}
            redirect-uri: ${google.redirect-uri}
            authorization-grant-type: authorization_code
            client-authentication-method: POST
            client-name: Google
            scope:
              - profile
              - email

  data:
    redis:
      port: ${spring.data.redis.port}
      host: ${spring.data.redis.host}

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  api:
    url: ${application.spring.api.url}
    key: ${application.spring.api.key}

logging:
  level:
    com.drugbox.common: debug

jwt:
  secret: ${application.jwt.secret}
  secret_refresh: ${application.jwt.secret_refresh}
